### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [aheckmann/mpath#12]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by vkarpov15** [comment]
Added a SECURITY.md file :+1: Please send me an email to report the issue.

**Comment by zidingz** [comment]
Thanks!

**Comment by JamieSlome** [comment]
@vkarpov15 - are we able to confirm what the patch for the report was?

https://huntr.dev/bounties/74f8e882-c07d-4b49-aa5c-bada506a1ebc/

We can then go ahead and publish a CVE for you!
